### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by iT-Boyer** [ryanolsonk/LLDB-QuickLook#10]
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/usr/local/opt/chisel/libexec/fbchisellldb.py", line 27, in loadCommandsInDirectory
    module = imp.load_source(fileName, os.path.join(commandsDirectory, file))
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 916, in get_code
  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/boyer/.myPyDir/lldb_quick_look.py", line 102
    except DebuggerError, err:
                        ^
SyntaxError: invalid syntax
```

**Comment by deets** [comment]
You need to convert the Code to Python 3.
