### ISSUE TITLE
Cannot run command:ql, got error,need help

### ISSUE THREAD

**Issue by btxkenshin** [ryanolsonk/LLDB-QuickLook#2]
(lldb) po self.view
$0 = 0x08992ca0 <UIView: 0x8992ca0; frame = (0 20; 320 460); autoresize = RM+BM; layer = <CALayer: 0x89948a0>>
(lldb) ql self.view
Traceback (most recent call last):
  File "/Users/kenshin/Documents/MyCollection/Xcode/LLDB-QuickLook/lldb_quick_look.py", line 100, in quick_look_command
    savedFilePath = get_data_and_save(debugger, expression, options.filename)
  File "/Users/kenshin/Documents/MyCollection/Xcode/LLDB-QuickLook/lldb_quick_look.py", line 166, in get_data_and_save
    options.SetIgnoreBreakpoints()
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/Python/lldb/**init**.py", line 3217, in <lambda>
    **getattr** = lambda self, name: _swig_getattr(self, SBExpressionOptions, name)
  File "/Applications/Xcode.app/Contents/SharedFrameworks/LLDB.framework/Versions/A/Resources/Python/lldb/__init__.py", line 78, in _swig_getattr
    raise AttributeError(name)
AttributeError: SetIgnoreBreakpoints
(lldb)

It seems that in  lldb_quick_look.py of line 166 ,the function 'SetIgnoreBreakpoints' not exist to the caller 'options'.
What should i do?

**Comment by ryanolsonk** [comment]
Which version of Xcode are you using? The tool requires Xcode 5. I will add a note to the readme to make this clear.

**Comment by btxkenshin** [comment]
@ryanolsonk 
Got,am still using Xcode 4.x,Thank you very much.I will try Xcode 5
